export { default as App } from './app/app'
export { default as Navbar } from './navbar/navbar'
export { default as Footer } from './footer/footer'
export { default as Main } from './main/main'
export { default as Whatwedo } from './whatwedo/whatwedo'
export { default as TestCard} from './TestCard/testcard'
export { default as Contact } from './contact/contact'
export { default as Tests} from './testpage/TestPage'
export { default as Reading} from './Reading/reading'
export { default as Listening} from './listening/listening'
export { default as Writing } from './writing/writing'
export { default as TestDetail} from './TestDetail/testDetail'
export { default as TestTimer} from './testTimer/testTimer'
export { default as Test } from './Tests/tests'

export { default as ListeningTable } from '../tables/Listening'
export { default as ReadingTable } from '../tables/Reading'
export { default as WritingView } from '../tables/Writing'

export { default as UserDetail } from '../pages/UserDetail'
export { default as Teachers } from '../pages/Teachers'
export { default as Home } from '../pages/Home'
