export { default as App } from './app/app'
export { default as Navbar } from './navbar/navbar'
export { default as Footer } from './footer/footer'
export { default as Main } from './main/main'
export { default as Whatwedo } from './whatwedo/whatwedo'
export { default as Test} from './Tests/tests'
export {default as Contact} from './contact/contact'
